# Generated by Django 3.2 on 2021-05-03 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Firstname', models.CharField(max_length=15)),
                ('Lastname', models.CharField(max_length=15, null=True)),
                ('email', models.CharField(max_length=20)),
            ],
        ),
    ]
