# Generated by Django 3.2 on 2021-05-04 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_book_slot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advisor',
            name='Lastname',
        ),
    ]
