# Generated by Django 3.2 on 2021-05-04 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_remove_advisor_lastname'),
    ]

    operations = [
        migrations.AddField(
            model_name='advisor',
            name='imageurl',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
