# Generated by Django 3.2 on 2021-05-05 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0009_auto_20210505_0642'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='slot',
        ),
        migrations.AddField(
            model_name='book',
            name='slot_date',
            field=models.DateField(null=True),
        ),
    ]
