# Generated by Django 3.2 on 2021-05-05 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0010_auto_20210505_0904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='slot_date',
            field=models.DateTimeField(null=True),
        ),
    ]
